### ISSUE TITLE
crashed when exit

### ISSUE THREAD

**Issue by xengine-qyt** [liyunfan1223/mod-playerbots#212]
**Describe the bug**
crashed when exist 

**Commit hash**
azero:[0a1570e](https://github.com/liyunfan1223/azerothcore-wotlk/commit/0a1570ec52a6380e4114c3f78354ff95125574f1)
playbot:[85bab82](https://github.com/liyunfan1223/mod-playerbots/commit/85bab825a17afb20f87f244f8270d9c97b642b9b)

**To Reproduce**
sudo ./worldserver
ctrl + c

**Expected behavior**
The azerothcore version does not crash

**Screenshots**
![image](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/18b5c8ea-37db-4a63-86c4-d6bea3da9c8d)

**Desktop (please complete the following information):**
 - ubuntu22.04.4 -x64

**Additional context**

**Comment by noisiver** [comment]
I have the same thing, as I assume most if not all people do. I figured I'd throw in data from gdb to hopefully aid in finding the cause. I don't see any mention of bad_alloc in my log though, strangely. That may or may not be because I'm running ARM and not x64.

```
2542651.939787 [Thread debugging using libthread_db enabled]
2542651.939839 Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
2542651.980965 [New Thread 0xfffff3ffd8a0 (LWP 774869)]
2542651.981368 [New Thread 0xfffff37ed8a0 (LWP 774870)]
2542651.987450 [New Thread 0xfffff2d5d8a0 (LWP 774871)]
2542652.026945 [New Thread 0xfffff254d8a0 (LWP 774872)]
2542652.120102 [New Thread 0xfffff1d3d8a0 (LWP 774873)]
2542652.295810 [New Thread 0xfffff122d8a0 (LWP 774874)]
2542662.879389 [New Thread 0xffff849fd8a0 (LWP 774877)]
2542662.881439 [New Thread 0xffff841ed8a0 (LWP 774878)]
2542662.881859 [New Thread 0xffff839dd8a0 (LWP 774879)]
2542662.882078 [New Thread 0xffff831cd8a0 (LWP 774880)]
2542664.129969 [New Thread 0xffff749bd8a0 (LWP 774881)]
2542664.131006 [Thread 0xffff749bd8a0 (LWP 774881) exited]
2542690.724189 [New Thread 0xffff749bd8a0 (LWP 774884)]
2542691.296128 [New Thread 0xfffe291fd8a0 (LWP 774885)]
2542691.296566 [New Thread 0xfffe289ed8a0 (LWP 774886)]
2542691.308608 [New Thread 0xfffe273fd8a0 (LWP 774887)]
2542691.308820 [Thread 0xfffe273fd8a0 (LWP 774887) exited]
2542693.678289 [Thread 0xfffe289ed8a0 (LWP 774886) exited]
2542693.678570 [Thread 0xfffff37ed8a0 (LWP 774870) exited]
2542693.678647 [Thread 0xfffff3ffd8a0 (LWP 774869) exited]
2542693.871099 [Thread 0xfffe291fd8a0 (LWP 774885) exited]
2542693.871292 [Thread 0xffff749bd8a0 (LWP 774884) exited]
2542696.121690 [Thread 0xffff849fd8a0 (LWP 774877) exited]
2542696.122067 [Thread 0xffff831cd8a0 (LWP 774880) exited]
2542696.122118 [Thread 0xffff839dd8a0 (LWP 774879) exited]
2542696.122998 [Thread 0xffff841ed8a0 (LWP 774878) exited]
2542696.123242 [Thread 0xfffff254d8a0 (LWP 774872) exited]
2542696.127164 [Thread 0xfffff1d3d8a0 (LWP 774873) exited]
2542696.129548 [Thread 0xfffff122d8a0 (LWP 774874) exited]
2542696.129577 [Thread 0xfffff2d5d8a0 (LWP 774871) exited]

Thread 1 "worldserver" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=281474841952288, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
2542696.222869 44	./nptl/pthread_kill.c: No such file or directory.
#0  __pthread_kill_implementation (threadid=281474841952288, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x0000fffff6d0f254 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x0000fffff6cca67c in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x0000fffff6cb7130 in __GI_abort () at ./stdlib/abort.c:79
#4  0x0000fffff6fb62dc in __gnu_cxx::__verbose_terminate_handler() () from /lib/aarch64-linux-gnu/libstdc++.so.6
#5  0x0000fffff6fb2abc in ?? () from /lib/aarch64-linux-gnu/libstdc++.so.6
#6  0x0000fffff6fb2b20 in std::terminate() () from /lib/aarch64-linux-gnu/libstdc++.so.6
#7  0x0000aaaaab032168 in __clang_call_terminate ()
#8  0x0000aaaaabd33210 in Group::~Group (this=0xffffb98b3f80) at /home/ubuntu/azerothcore/world1/source/src/server/game/Groups/Group.cpp:106
#9  0x0000aaaaabd3c5d8 in GroupMgr::~GroupMgr (this=0xaaaaacb2dee0 <GroupMgr::instance()::instance>) at /home/ubuntu/azerothcore/world1/source/src/server/game/Groups/GroupMgr.cpp:33
#10 0x0000fffff6cccde8 in __run_exit_handlers (status=0, listp=0xfffff6e2b730 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
#11 0x0000fffff6cccf0c in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
#12 0x0000fffff6cb7400 in __libc_start_call_main (main=main@entry=0xaaaaab029a14 <main(int, char**)>, argc=argc@entry=1, argv=argv@entry=0xfffffffff438) at ../sysdeps/nptl/libc_start_call_main.h:74
#13 0x0000fffff6cb74cc in __libc_start_main_impl (main=0xaaaaab029a14 <main(int, char**)>, argc=1, argv=0xfffffffff438, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:392
#14 0x0000aaaaab029930 in _start ()
#0  __pthread_kill_implementation (threadid=281474841952288, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
        tid = 774867
        ret = 0
        pd = 0xfffff7f7c020
        old_mask = {__val = {281474822350988, 0, 281474842237112, 0, 281474842487496, 281474841954272, 4294967295, 281474842483536, 281474823885856, 281474842222592, 4294967295, 0, 281474822180328, 281474842223936, 281474842490632, 281474976706752}}
        ret = <optimized out>
#1  0x0000fffff6d0f254 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
No locals.
#2  0x0000fffff6cca67c in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x0000fffff6cb7130 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xfffff7f7e048, sa_sigaction = 0xfffff7f7e048}, sa_mask = {__val = {281474780186672, 109330211561823, 7016437113889059923, 17298044693753364480, 0, 17298308644996116495, 17298308644996116495, 4278190080, 4278190080, 0, 0, 0, 0, 281473003883776, 281472997671424, 281473003883008}}, sa_flags = -1972828416, sa_restorer = 0xfffff7134d60 <abort@got[plt]>}
        sigs = {__val = {32, 281474822590588, 1, 281474822180328, 281474822271052, 1, 281474976706592, 281474822587452, 64, 29, 0, 0, 1125899305732192, 2, 1, 13308606101455164672}}
#4  0x0000fffff6fb62dc in __gnu_cxx::__verbose_terminate_handler() () from /lib/aarch64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x0000fffff6fb2abc in ?? () from /lib/aarch64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x0000fffff6fb2b20 in std::terminate() () from /lib/aarch64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x0000aaaaab032168 in __clang_call_terminate ()
No symbol table info available.
#8  0x0000aaaaabd33210 in Group::~Group (this=0xffffb98b3f80) at /home/ubuntu/azerothcore/world1/source/src/server/game/Groups/Group.cpp:106
        itr = <optimized out>
#9  0x0000aaaaabd3c5d8 in GroupMgr::~GroupMgr (this=0xaaaaacb2dee0 <GroupMgr::instance()::instance>) at /home/ubuntu/azerothcore/world1/source/src/server/game/Groups/GroupMgr.cpp:33
        itr = {first = 2, second = 0xffffb98b3f80}
#10 0x0000fffff6cccde8 in __run_exit_handlers (status=0, listp=0xfffff6e2b730 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = 0xaaaaabd3c548 <GroupMgr::~GroupMgr()>
        arg = 0xaaaaacb2dee0 <GroupMgr::instance()::instance>
        f = <optimized out>
        new_exitfn_called = <optimized out>
        cur = 0xfffff44dae00
#11 0x0000fffff6cccf0c in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
No locals.
#12 0x0000fffff6cb7400 in __libc_start_call_main (main=main@entry=0xaaaaab029a14 <main(int, char**)>, argc=argc@entry=1, argv=argv@entry=0xfffffffff438) at ../sysdeps/nptl/libc_start_call_main.h:74
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {281474976707640, 1, 187650014983176, 281474842484800, 187649990236692, 281474823790592, 0, 281474976707656, 187650014983176, 0, 281474976707264, 9565362114631146123, 4655643828679500911, 9565362114514983819, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0xfffff6e2a000 <sys_siglist+424>, 0xfffff6e2b080 <_dl_audit_preinit@got.plt>}, data = {prev = 0x0, cleanup = 0x0, canceltype = -152920064}}}
        not_first_call = <optimized out>
#13 0x0000fffff6cb74cc in __libc_start_main_impl (main=0xaaaaab029a14 <main(int, char**)>, argc=1, argv=0xfffffffff438, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:392
No locals.
#14 0x0000aaaaab029930 in _start ()
No symbol table info available.
  Id   Target Id                                        Frame 
* 1    Thread 0xfffff7f7c020 (LWP 774867) "worldserver" __pthread_kill_implementation (threadid=281474841952288, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44

Thread 1 (Thread 0xfffff7f7c020 (LWP 774867) "worldserver"):
#0  __pthread_kill_implementation (threadid=281474841952288, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
        tid = 774867
        ret = 0
        pd = 0xfffff7f7c020
        old_mask = {__val = {281474822350988, 0, 281474842237112, 0, 281474842487496, 281474841954272, 4294967295, 281474842483536, 281474823885856, 281474842222592, 4294967295, 0, 281474822180328, 281474842223936, 281474842490632, 281474976706752}}
        ret = <optimized out>
#1  0x0000fffff6d0f254 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
No locals.
#2  0x0000fffff6cca67c in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x0000fffff6cb7130 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xfffff7f7e048, sa_sigaction = 0xfffff7f7e048}, sa_mask = {__val = {281474780186672, 109330211561823, 7016437113889059923, 17298044693753364480, 0, 17298308644996116495, 17298308644996116495, 4278190080, 4278190080, 0, 0, 0, 0, 281473003883776, 281472997671424, 281473003883008}}, sa_flags = -1972828416, sa_restorer = 0xfffff7134d60 <abort@got[plt]>}
        sigs = {__val = {32, 281474822590588, 1, 281474822180328, 281474822271052, 1, 281474976706592, 281474822587452, 64, 29, 0, 0, 1125899305732192, 2, 1, 13308606101455164672}}
#4  0x0000fffff6fb62dc in __gnu_cxx::__verbose_terminate_handler() () from /lib/aarch64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x0000fffff6fb2abc in ?? () from /lib/aarch64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x0000fffff6fb2b20 in std::terminate() () from /lib/aarch64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x0000aaaaab032168 in __clang_call_terminate ()
No symbol table info available.
#8  0x0000aaaaabd33210 in Group::~Group (this=0xffffb98b3f80) at /home/ubuntu/azerothcore/world1/source/src/server/game/Groups/Group.cpp:106
        itr = <optimized out>
#9  0x0000aaaaabd3c5d8 in GroupMgr::~GroupMgr (this=0xaaaaacb2dee0 <GroupMgr::instance()::instance>) at /home/ubuntu/azerothcore/world1/source/src/server/game/Groups/GroupMgr.cpp:33
        itr = {first = 2, second = 0xffffb98b3f80}
#10 0x0000fffff6cccde8 in __run_exit_handlers (status=0, listp=0xfffff6e2b730 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = 0xaaaaabd3c548 <GroupMgr::~GroupMgr()>
        arg = 0xaaaaacb2dee0 <GroupMgr::instance()::instance>
        f = <optimized out>
        new_exitfn_called = <optimized out>
        cur = 0xfffff44dae00
#11 0x0000fffff6cccf0c in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
No locals.
#12 0x0000fffff6cb7400 in __libc_start_call_main (main=main@entry=0xaaaaab029a14 <main(int, char**)>, argc=argc@entry=1, argv=argv@entry=0xfffffffff438) at ../sysdeps/nptl/libc_start_call_main.h:74
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {281474976707640, 1, 187650014983176, 281474842484800, 187649990236692, 281474823790592, 0, 281474976707656, 187650014983176, 0, 281474976707264, 9565362114631146123, 4655643828679500911, 9565362114514983819, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0xfffff6e2a000 <sys_siglist+424>, 0xfffff6e2b080 <_dl_audit_preinit@got.plt>}, data = {prev = 0x0, cleanup = 0x0, canceltype = -152920064}}}
        not_first_call = <optimized out>
#13 0x0000fffff6cb74cc in __libc_start_main_impl (main=0xaaaaab029a14 <main(int, char**)>, argc=1, argv=0xfffffffff438, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:392
No locals.
#14 0x0000aaaaab029930 in _start ()
No symbol table info available.
```

**Comment by xengine-qyt** [comment]
i am configure to generate coredump ,but i dont know why does not generate.so i cant provide bt stack information
![image](https://github.com/liyunfan1223/mod-playerbots/assets/37919215/804f2249-c5ff-486c-bcae-6dafee76b8e5)

**Comment by noisiver** [comment]
Why did you close the issue?

**Comment by xengine-qyt** [comment]
> Why did you close the issue?

I updated to the latest version,and not crashed after reset rebot
