### ISSUE TITLE
German texts in 'ai_playerbot_texts' cause crashes

### ISSUE THREAD

**Issue by MichaTausKamR** [liyunfan1223/mod-playerbots#518]
**Describe the bug**
When chatting with german texts, the server crashes.

**Commit hash**
The hash of the current commit.

**To Reproduce**
1. Go to your db-manager
2. Click on the mentioned table
3. Add texts with german umlauts, other special characters

**Expected behavior**
Don't crash

[gdb.txt](https://github.com/user-attachments/files/16950141/gdb.txt)

**Comment by atidot3** [comment]
I'm french and i'd like to do thousand of joke based on that but unfortunatly its unrelated.

#9  0x00007ffff7048265 in std::__throw_bad_alloc() () from /lib/x86_64-linux-gn\
u/libstdc++.so.6
#10 0x0000555556ff35fc in handleOOM(unsigned long, bool) ()

You've reach max RAM usage

**Comment by MichaTausKamR** [comment]
Alright, so when I deleted the german texts, the problem occured far more less than that. The machine doesn't use even half of the ram.

**Comment by hermensbas** [comment]
> Alright, so when I deleted the german texts, the problem occured far more less than that. The machine doesn't use even half of the ram.

thats interesting is related to RAM usage by adding or changes texts...

**Comment by hermensbas** [comment]
The language support sure, but the mem usage increase needs to be verified and looked into

**Comment by Raz0r1337** [comment]
A temporary workaround for the crashes could be to use alternate patterns like ae, ue, oe, ss instead of ä, ü, ö, ß. When it gets fixed this should be easy to change to the umlauts with a macro.

**Comment by Raz0r1337** [comment]
I've been working on a German translation for the chatter texts for some time. Today I got to the point where I could try it out. I haven't noticed any problems. No crashes and all umlauts are displayed correctly. Something must have changed on your site. Or there has already been an update that has fixed this problem.

**Comment by Dreathean** [comment]
@MichaTausKamR @Raz0r1337 so is this fixed and good to close?

**Comment by Raz0r1337** [comment]
I would say yes.
I have no issues with German umlauts for weeks.

Test it yourself before closing this.
My translation PR is merged into Playerbots.

Put only playerbot_text.sql in your player it DB and there it is. 😉
