### ISSUE TITLE
AI_VALUE(std::list<ObjectGuid>, "nearest game objects") seems to be causing segfault in specific circumstance

### ISSUE THREAD

**Issue by acore-crap** [liyunfan1223/mod-playerbots#704]
**Describe the bug**
  see title

**Commit hash**
  d54bfb303e9 (latest as of posting)

**To Reproduce**
  go through dark portal with playerbots in tow
  pick up short quest line leading to Vlagga Freyfeather
  talk to Vlagga Freyfeather, accept Journey to Thrallmar
  tell playerbots "talk" and then "talk 1" so they take the initial flight to Thrallmar
  fly to Thrallmar
  server crash the moment bots dismount

**Expected behavior**
  the server not experiencing a segfault in these circumstances, i suppose

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
```
Thread 23 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff94e006c0 (LWP 953961)]
0x0000555555eeff5b in QuestAction::Execute (this=0x7ffea3d18390, event=...) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/QuestAction.cpp:56
56	    std::list<ObjectGuid> gos = AI_VALUE(std::list<ObjectGuid>, "nearest game objects");
#0  0x0000555555eeff5b in QuestAction::Execute (this=0x7ffea3d18390, event=...) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/QuestAction.cpp:56
#1  0x0000555555e70736 in Engine::ListenAndExecute (this=this@entry=0x7fff1c2b3c00, action=action@entry=0x7ffea3d18390, event=...) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Engine.cpp:629
#2  0x0000555555e6e1fe in Engine::DoNextAction (this=0x7fff1c2b3c00, unit=<optimized out>, depth=<optimized out>, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Engine.cpp:214
#3  0x0000555555d81849 in PlayerbotAI::DoNextAction (this=this@entry=0x7fff1ab9aa00, min=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:1322
#4  0x0000555555d810a1 in PlayerbotAI::UpdateAIInternal (this=0x7fff1ab9aa00, elapsed=<optimized out>, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:484
#5  0x0000555555d80075 in PlayerbotAI::UpdateAI (this=0x7fff1ab9aa00, elapsed=19, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:408
#6  0x0000555555c69484 in PlayerbotsPlayerScript::OnAfterUpdate (this=<optimized out>, player=0x7fff1c18f6c0, diff=19) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/Playerbots.cpp:117
#7  0x0000555556ba602b in std::function<void (PlayerScript*)>::operator()(PlayerScript*) const (this=0x7fff94dfe258, __args=0x7ffff20335d0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_function.h:591
#8  ExecuteScript<PlayerScript>(std::function<void (PlayerScript*)>) (executeHook=...) at /home/hello/wow/azerothcore-wotlk/src/server/game/Scripting/ScriptMgrMacros.h:63
#9  ScriptMgr::OnAfterPlayerUpdate (this=<optimized out>, player=0x7fff1c18f6c0, diff=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/PlayerScript.cpp:224
#10 0x00005555568a9fad in Player::Update (this=0x7fff1c18f6c0, p_time=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Entities/Player/PlayerUpdates.cpp:425
#11 0x0000555556ae845b in Map::Update (this=0x7fffa431dc00, t_diff=0, s_diff=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/Map.cpp:768
#12 0x0000555556afe3dd in MapUpdateRequest::call (this=0x7fff30491980) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:44
#13 0x0000555556afdea8 in MapUpdater::WorkerThread (this=0x5555579f8108 <MapMgr::instance()::instance+216>) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:156
#14 0x00007ffff6cecdb4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007ffff689ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#16 0x00007ffff6929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
#0  0x0000555555eeff5b in QuestAction::Execute (this=0x7ffea3d18390, event=...) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/QuestAction.cpp:56
        npcs = std::vector of length 24, capacity 24 = {{static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17383898286359838756}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17383897702495944738}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391331004064850}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391285068047441}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240306435151}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994638}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994637}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994636}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994635}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994634}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994633}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994632}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994631}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994630}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994629}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994628}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994627}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391005895173186}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994585}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391331155059746}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391276679439391}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994586}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391331155059777}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391005895173183}}
        gos = std::__cxx11::list<error reading variable: Cannot access memory at address 0x1>
        guid = <optimized out>
        master = <optimized out>
        result = <optimized out>
#1  0x0000555555e70736 in Engine::ListenAndExecute (this=this@entry=0x7fff1c2b3c00, action=action@entry=0x7ffea3d18390, event=...) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Engine.cpp:629
        actionExecuted = false
#2  0x0000555555e6e1fe in Engine::DoNextAction (this=0x7fff1c2b3c00, unit=<optimized out>, depth=<optimized out>, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Engine.cpp:214
        pmo = 0x0
        relevance = 100
        actionNode = 0x7fff4cc3dc50
        action = 0x7ffea3d18390
        event = {_vptr$Event = 0x555557696760 <vtable for Event+16>, source = "talk", param = "1", packet = {<ByteBuffer> = {_vptr$ByteBuffer = 0x55555768f1e0 <vtable for WorldPacket+16>, static DEFAULT_SIZE = 4096, _rpos = 0, _wpos = 0, _storage = std::vector of length 0, capacity 0}, m_opcode = 0, m_receivedTime = std::chrono::_V2::steady_clock time_point = { 0ns }}, owner = 0x7fff1bbb0ec0}
        skipPrerequisites = <optimized out>
        actionExecuted = false
        basket = <optimized out>
        currentTime = 1731282707
        iterations = 0
        iterationsPerTick = 60
#3  0x0000555555d81849 in PlayerbotAI::DoNextAction (this=this@entry=0x7fff1ab9aa00, min=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:1322
        minimal = <optimized out>
        group = <optimized out>
        masterBotAI = <optimized out>
        hasMountAura = <optimized out>
#4  0x0000555555d810a1 in PlayerbotAI::UpdateAIInternal (this=0x7fff1ab9aa00, elapsed=<optimized out>, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:484
        mapString = "530"
        helper = {aiObjectContext = 0x7fff8dabf840}
        pmo = 0x0
#5  0x0000555555d80075 in PlayerbotAI::UpdateAI (this=0x7fff1ab9aa00, elapsed=19, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:408
        currentSpell = <optimized out>
        min = false
#6  0x0000555555c69484 in PlayerbotsPlayerScript::OnAfterUpdate (this=<optimized out>, player=0x7fff1c18f6c0, diff=19) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/Playerbots.cpp:117
        botAI = 0x0
#7  0x0000555556ba602b in std::function<void (PlayerScript*)>::operator()(PlayerScript*) const (this=0x7fff94dfe258, __args=0x7ffff20335d0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_function.h:591
No locals.
#8  ExecuteScript<PlayerScript>(std::function<void (PlayerScript*)>) (executeHook=...) at /home/hello/wow/azerothcore-wotlk/src/server/game/Scripting/ScriptMgrMacros.h:63
        script = @0x7ffff2033628: 0x7ffff20335d0
        __begin0 = {first = 10, second = 0x7ffff20335d0}
        __begin0 = <optimized out>
        __range1 = <optimized out>
        __end0 = <optimized out>
        script = <optimized out>
        scriptID = <optimized out>
#9  ScriptMgr::OnAfterPlayerUpdate (this=<optimized out>, player=0x7fff1c18f6c0, diff=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/PlayerScript.cpp:224
No locals.
#10 0x00005555568a9fad in Player::Update (this=0x7fff1c18f6c0, p_time=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Entities/Player/PlayerUpdates.cpp:425
        now = 1731282707
        lastTick = 1731282707
        pet = <optimized out>
#11 0x0000555556ae845b in Map::Update (this=0x7fffa431dc00, t_diff=0, s_diff=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/Map.cpp:768
        player = 0x7ffef3e21ac0
        updater = {i_timeDiff = 1457256458, i_largeOnly = 85}
        grid_object_update = {i_visitor = @0x555555c0f0a0}
        world_object_update = {i_visitor = @0x0}
        largeObjectUpdater = {i_timeDiff = 102, i_largeOnly = false}
        grid_large_object_update = {i_visitor = @0x555555c0f080}
        world_large_object_update = {i_visitor = @0x7fff94dfe590}
        updateList = <optimized out>
#12 0x0000555556afe3dd in MapUpdateRequest::call (this=0x7fff30491980) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:44
        __ac_metric_stop_watch43 = {_logger = {this = 0x7fff30491980}, _startTime = std::chrono::_V2::steady_clock time_point = { 0ns }}
#13 0x0000555556afdea8 in MapUpdater::WorkerThread (this=0x5555579f8108 <MapMgr::instance()::instance+216>) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:156
        request = 0x7fff30491980
#14 0x00007ffff6cecdb4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#15 0x00007ffff689ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140735691097792, -8875363365039866041, 140735691097792, -6408, 0, 140737488342176, -8875363365027283129, -8875287927191339193}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#16 0x00007ffff6929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
No locals.
  Id   Target Id                                        Frame 
  1    Thread 0x7ffff7517fc0 (LWP 953770) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555579f8228 <MapMgr::instance()::instance+504>) at ./nptl/futex-internal.c:57
  2    Thread 0x7ffff5e006c0 (LWP 953774) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=32767, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644c89c) at ./nptl/futex-internal.c:57
  3    Thread 0x7ffff54006c0 (LWP 953775) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=32767, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644c898) at ./nptl/futex-internal.c:57
  4    Thread 0x7ffff4a006c0 (LWP 953776) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644c89c) at ./nptl/futex-internal.c:57
  5    Thread 0x7ffff40006c0 (LWP 953777) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644c898) at ./nptl/futex-internal.c:57
  6    Thread 0x7ffff36006c0 (LWP 953778) "worldserver" 0x00007ffff692a042 in epoll_wait (epfd=6, events=0x7ffff35fde10, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  7    Thread 0x7ffff2c006c0 (LWP 953779) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644c898) at ./nptl/futex-internal.c:57
  8    Thread 0x7ffff1e006c0 (LWP 953780) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=838589065, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a364) at ./nptl/futex-internal.c:57
  9    Thread 0x7ffff14006c0 (LWP 953781) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=838589065, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a364) at ./nptl/futex-internal.c:57
  10   Thread 0x7ffff06006c0 (LWP 953782) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=21845, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a2a0) at ./nptl/futex-internal.c:57
  11   Thread 0x7fffefc006c0 (LWP 953783) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=21845, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a2a0) at ./nptl/futex-internal.c:57
  12   Thread 0x7fffef2006c0 (LWP 953784) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=21845, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a2a4) at ./nptl/futex-internal.c:57
  13   Thread 0x7fffee0006c0 (LWP 953807) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a1e4) at ./nptl/futex-internal.c:57
  14   Thread 0x7fffed6006c0 (LWP 953808) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a1e0) at ./nptl/futex-internal.c:57
  15   Thread 0x7fffecc006c0 (LWP 953809) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a1e0) at ./nptl/futex-internal.c:57
  16   Thread 0x7fffea6006c0 (LWP 953828) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=21845, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a420) at ./nptl/futex-internal.c:57
  17   Thread 0x7fffe9c006c0 (LWP 953829) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=21845, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a424) at ./nptl/futex-internal.c:57
  18   Thread 0x7fffe92006c0 (LWP 953830) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=21845, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a424) at ./nptl/futex-internal.c:57
  19   Thread 0x7fffe88006c0 (LWP 953831) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=21845, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffff644a424) at ./nptl/futex-internal.c:57
  20   Thread 0x7fff970006c0 (LWP 953958) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=32767, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555579f81a8 <MapMgr::instance()::instance+376>) at ./nptl/futex-internal.c:57
  21   Thread 0x7fff962006c0 (LWP 953959) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=32767, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555579f81a8 <MapMgr::instance()::instance+376>) at ./nptl/futex-internal.c:57
  22   Thread 0x7fff958006c0 (LWP 953960) "worldserver" 0x00007ffff6898d61 in __futex_abstimed_wait_common64 (private=32767, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555579f81a8 <MapMgr::instance()::instance+376>) at ./nptl/futex-internal.c:57
* 23   Thread 0x7fff94e006c0 (LWP 953961) "worldserver" 0x0000555555eeff5b in QuestAction::Execute (this=0x7ffea3d18390, event=<optimized out>) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/QuestAction.cpp:56
  25   Thread 0x7fff824006c0 (LWP 953981) "worldserver" 0x00007ffff692a042 in epoll_wait (epfd=41, events=0x7fff823fdd60, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  26   Thread 0x7fff81a006c0 (LWP 953982) "worldserver" 0x00007ffff692a042 in epoll_wait (epfd=44, events=0x7fff819fdd60, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  27   Thread 0x7fff808006c0 (LWP 953983) "worldserver" 0x00007ffff692603f in pselect64_syscall (sigmask=<optimized out>, timeout=<optimized out>, exceptfds=0x7fff807fe400, writefds=0x0, readfds=0x7fff807fe480, nfds=1) at ../sysdeps/unix/sysv/linux/pselect.c:34
  28   Thread 0x7fff7fe006c0 (LWP 953984) "worldserver" 0x00007ffff68ecadf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fff7fdfe588, rem=0x7fff7fdfe588) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
...
(a bunch of epoll_wait threads, message too long)
...
Thread 23 (Thread 0x7fff94e006c0 (LWP 953961) "worldserver"):
#0  0x0000555555eeff5b in QuestAction::Execute (this=0x7ffea3d18390, event=<optimized out>) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/actions/QuestAction.cpp:56
        npcs = std::vector of length 24, capacity 24 = {{static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17383898286359838756}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17383897702495944738}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391331004064850}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391285068047441}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240306435151}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994638}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994637}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994636}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994635}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994634}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994633}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994632}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994631}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994630}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994629}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994628}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994627}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391005895173186}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994585}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391331155059746}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391276679439391}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391240188994586}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391331155059777}, {static Empty = {static Empty = <same as static member of an already seen type>, _guid = 0}, _guid = 17379391005895173183}}
        gos = std::__cxx11::list<error reading variable: Cannot access memory at address 0x1>
        guid = <optimized out>
        master = <optimized out>
        result = <optimized out>
#1  0x0000555555e70736 in Engine::ListenAndExecute (this=this@entry=0x7fff1c2b3c00, action=action@entry=0x7ffea3d18390, event=...) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Engine.cpp:629
        actionExecuted = false
#2  0x0000555555e6e1fe in Engine::DoNextAction (this=0x7fff1c2b3c00, unit=<optimized out>, depth=<optimized out>, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/strategy/Engine.cpp:214
        pmo = 0x0
        relevance = 100
        actionNode = 0x7fff4cc3dc50
        action = 0x7ffea3d18390
        event = {_vptr$Event = 0x555557696760 <vtable for Event+16>, source = "talk", param = "1", packet = {<ByteBuffer> = {_vptr$ByteBuffer = 0x55555768f1e0 <vtable for WorldPacket+16>, static DEFAULT_SIZE = 4096, _rpos = 0, _wpos = 0, _storage = std::vector of length 0, capacity 0}, m_opcode = 0, m_receivedTime = std::chrono::_V2::steady_clock time_point = { 0ns }}, owner = 0x7fff1bbb0ec0}
        skipPrerequisites = <optimized out>
        actionExecuted = false
        basket = <optimized out>
        currentTime = 1731282707
        iterations = 0
        iterationsPerTick = 60
#3  0x0000555555d81849 in PlayerbotAI::DoNextAction (this=this@entry=0x7fff1ab9aa00, min=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:1322
        minimal = <optimized out>
        group = <optimized out>
        masterBotAI = <optimized out>
        hasMountAura = <optimized out>
#4  0x0000555555d810a1 in PlayerbotAI::UpdateAIInternal (this=0x7fff1ab9aa00, elapsed=<optimized out>, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:484
        mapString = "530"
        helper = {aiObjectContext = 0x7fff8dabf840}
        pmo = 0x0
#5  0x0000555555d80075 in PlayerbotAI::UpdateAI (this=0x7fff1ab9aa00, elapsed=19, minimal=false) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/PlayerbotAI.cpp:408
        currentSpell = <optimized out>
        min = false
#6  0x0000555555c69484 in PlayerbotsPlayerScript::OnAfterUpdate (this=<optimized out>, player=0x7fff1c18f6c0, diff=19) at /home/hello/wow/azerothcore-wotlk/modules/mod-playerbots/src/Playerbots.cpp:117
        botAI = 0x0
#7  0x0000555556ba602b in std::function<void (PlayerScript*)>::operator()(PlayerScript*) const (this=0x7fff94dfe258, __args=0x7ffff20335d0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_function.h:591
No locals.
#8  ExecuteScript<PlayerScript>(std::function<void (PlayerScript*)>) (executeHook=...) at /home/hello/wow/azerothcore-wotlk/src/server/game/Scripting/ScriptMgrMacros.h:63
        script = @0x7ffff2033628: 0x7ffff20335d0
        __begin0 = {first = 10, second = 0x7ffff20335d0}
        __begin0 = <optimized out>
        __range1 = <optimized out>
        __end0 = <optimized out>
        script = <optimized out>
        scriptID = <optimized out>
#9  ScriptMgr::OnAfterPlayerUpdate (this=<optimized out>, player=0x7fff1c18f6c0, diff=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/PlayerScript.cpp:224
No locals.
#10 0x00005555568a9fad in Player::Update (this=0x7fff1c18f6c0, p_time=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Entities/Player/PlayerUpdates.cpp:425
        now = 1731282707
        lastTick = 1731282707
        pet = <optimized out>
#11 0x0000555556ae845b in Map::Update (this=0x7fffa431dc00, t_diff=0, s_diff=19) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/Map.cpp:768
        player = 0x7ffef3e21ac0
        updater = {i_timeDiff = 1457256458, i_largeOnly = 85}
        grid_object_update = {i_visitor = @0x555555c0f0a0}
        world_object_update = {i_visitor = @0x0}
        largeObjectUpdater = {i_timeDiff = 102, i_largeOnly = false}
        grid_large_object_update = {i_visitor = @0x555555c0f080}
        world_large_object_update = {i_visitor = @0x7fff94dfe590}
        updateList = <optimized out>
#12 0x0000555556afe3dd in MapUpdateRequest::call (this=0x7fff30491980) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:44
        __ac_metric_stop_watch43 = {_logger = {this = 0x7fff30491980}, _startTime = std::chrono::_V2::steady_clock time_point = { 0ns }}
#13 0x0000555556afdea8 in MapUpdater::WorkerThread (this=0x5555579f8108 <MapMgr::instance()::instance+216>) at /home/hello/wow/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:156
        request = 0x7fff30491980
#14 0x00007ffff6cecdb4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#15 0x00007ffff689ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140735691097792, -8875363365039866041, 140735691097792, -6408, 0, 140737488342176, -8875363365027283129, -8875287927191339193}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#16 0x00007ffff6929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
No locals.

...
(a whole bunch of __GI___futex_abstimed_wait_* worldserver threads, message too long)
```

**Comment by dedahr** [comment]
Can confirmt that and similar q in Borean Tundra [Magic Carpet Ride](https://www.wowhead.com/wotlk/quest=11636/magic-carpet-ride)
